/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "userApi",
            "endpoint": "https://apdeqmzdqg.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        },
        {
            "name": "rcmdApi",
            "endpoint": "https://yjd7dhm3e2.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        },
        {
            "name": "linkApi",
            "endpoint": "https://ykshpdbe56.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:4b55786a-34b7-4a66-984d-4d9131a5049b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_44pwiifEz",
    "aws_user_pools_web_client_id": "7k00h3rc1nbrp1cmdoatck73sh",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "rcmdaeabcd2cd371409ea687d5c0099597da123246-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "userMeta-dev",
            "region": "eu-west-1"
        },
        {
            "tableName": "rcmds-dev",
            "region": "eu-west-1"
        },
        {
            "tableName": "links-dev",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
